### ISSUE TITLE
how to evaluate?

### ISSUE THREAD

**Issue by lovejoker1102** [HannahHaensen/nerftrinsic_four#1]
I found here do not exist a eval file, and I train this project in fern scene, and got PSNR 20~21, do not reach the result provided in the paper. Maybe something wrong happens?

**Comment by HannahHaensen** [comment]
Hey @HaoyangHuang 

thanks for trying out our approach 

We will release the LLFF checkpoints in the next two to three months

We will also provide the evaluation script and details at that point as well

**Comment by HannahHaensen** [comment]
@HaoyangHuang please note we updated the readme with details about the release cycle. 

However, if you feel stuck have a look at the nerfmm repo.
