### ISSUE TITLE
How do you perform test-time optimization?

### ISSUE THREAD

**Issue by cmh1027** [HannahHaensen/nerftrinsic_four#2]
I see there's no test-time optimization code in this repo yet, and it seems eval_one_epoch reuses the image in training set. How do you perform test-time optimization for pose and focal length? Is focal length handled same as pose parameter in TTO?

**Comment by HannahHaensen** [comment]
@cmh1027 hey! thanks for the interest in our work, we follow the same evaluation strategy as NeRFmm.  
TTO for focal length is not required for LLFF for example at is the same values anyways.

**Comment by cmh1027** [comment]
Sorry for bothering, but how about dataset with different focal length like iFF?
